#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
COMPOSE_FILE="$SCRIPT_DIR/docker-compose.yml"
ENV_FILE="$SCRIPT_DIR/.env"

# Load .env if it exists
if [ -f "$ENV_FILE" ]; then
  set -a
  # shellcheck disable=SC1091
  source "$ENV_FILE"
  set +a
fi

# ── Helpers ─────────────────────────────────────────────────────

info()  { echo "  → $*"; }
error() { echo "  ✗ $*" >&2; }
ok()    { echo "  ✓ $*"; }

prompt() {
  local var_name="$1" prompt_text="$2" default="${3:-}"
  local input
  if [ -n "$default" ]; then
    printf "  %s [%s]: " "$prompt_text" "$default"
  else
    printf "  %s: " "$prompt_text"
  fi
  read -r input
  eval "$var_name=\"${input:-$default}\""
}

prompt_secret() {
  local var_name="$1" prompt_text="$2"
  local input="" char
  printf "  %s: " "$prompt_text"
  while IFS= read -rsn1 char; do
    if [[ -z "$char" ]]; then
      break
    elif [[ "$char" == $'\x7f' || "$char" == $'\b' ]]; then
      if [[ -n "$input" ]]; then
        input="${input%?}"
        printf '\b \b'
      fi
    else
      input+="$char"
      printf '*'
    fi
  done
  echo ""
  eval "$var_name=\"$input\""
}

generate_secret() {
  openssl rand -hex "$1" 2>/dev/null
}

check_docker() {
  if ! command -v docker &>/dev/null; then
    error "Docker is not installed."
    exit 1
  fi
  if ! docker compose version &>/dev/null; then
    error "Docker Compose v2 is not available."
    exit 1
  fi
}

# ── Commands ────────────────────────────────────────────────────

cmd_setup() {
  if [ -f "$ENV_FILE" ]; then
    info "Existing .env found."
    read -rp "  Overwrite with new configuration? [y/N]: " overwrite
    if [[ ! "${overwrite:-N}" =~ ^[Yy]$ ]]; then
      ok "Keeping existing configuration."
      return 0
    fi
  fi

  if ! command -v openssl &>/dev/null; then
    error "openssl is required to generate secrets. Please install it and try again."
    exit 1
  fi

  echo ""
  echo "  ── Configuration ──"
  echo ""

  prompt DOMAIN "Domain name (e.g. rallly.example.com)"
  prompt ACME_EMAIL "Email for SSL certificates" ""
  prompt SUPPORT_EMAIL "Support email shown to users" "$ACME_EMAIL"

  echo ""
  echo "  ── Email (SMTP) ──"
  echo ""
  prompt SMTP_HOST "SMTP host"
  prompt SMTP_PORT "SMTP port" "587"
  prompt SMTP_SECURE "SMTP uses SSL/TLS (true/false)" "true"
  prompt SMTP_USER "SMTP username"
  prompt_secret SMTP_PWD "SMTP password"

  echo ""
  info "Generating secrets..."

  local secret_password postgres_password s3_access_key s3_secret_key kv_token
  secret_password="$(generate_secret 32)"
  postgres_password="$(generate_secret 24)"
  s3_access_key="$(generate_secret 16)"
  s3_secret_key="$(generate_secret 32)"
  kv_token="$(generate_secret 32)"

  cat > "$ENV_FILE" <<ENVEOF
# Rallly Self-Hosted Configuration
# Generated by rallly.sh setup on $(date -u +"%Y-%m-%dT%H:%M:%SZ")

# ── Domain & SSL ──
DOMAIN=$DOMAIN
ACME_EMAIL=$ACME_EMAIL

# ── App Settings ──
SECRET_PASSWORD=$secret_password
SUPPORT_EMAIL=$SUPPORT_EMAIL

# ── SMTP ──
SMTP_HOST=$SMTP_HOST
SMTP_PORT=$SMTP_PORT
SMTP_SECURE=$SMTP_SECURE
SMTP_USER=$SMTP_USER
SMTP_PWD=$SMTP_PWD

# ── Auto-configured ──
POSTGRES_PASSWORD=$postgres_password
S3_ACCESS_KEY_ID=$s3_access_key
S3_SECRET_ACCESS_KEY=$s3_secret_key
KV_TOKEN=$kv_token
ENVEOF

  chmod 600 "$ENV_FILE"
  ok "Configuration saved to $ENV_FILE"
}

cmd_start() {
  check_docker
  if [ ! -f "$ENV_FILE" ]; then
    error "No .env file found. Run './rallly.sh setup' first."
    exit 1
  fi
  docker compose -f "$COMPOSE_FILE" up -d
  echo ""
  echo "Rallly is starting at https://${DOMAIN:-localhost}"
  echo "Run './rallly.sh logs' to watch startup progress."
}

cmd_stop() {
  check_docker
  docker compose -f "$COMPOSE_FILE" down
  echo "Rallly has been stopped."
}

cmd_restart() {
  check_docker
  docker compose -f "$COMPOSE_FILE" restart
  echo "Rallly has been restarted."
}

cmd_update() {
  check_docker
  echo "Pulling latest images..."
  docker compose -f "$COMPOSE_FILE" pull
  echo ""
  echo "Recreating containers..."
  docker compose -f "$COMPOSE_FILE" up -d --remove-orphans
  echo ""
  echo "Update complete."
  docker compose -f "$COMPOSE_FILE" ps
}

cmd_logs() {
  check_docker
  local service="${1:-}"
  if [ -n "$service" ]; then
    docker compose -f "$COMPOSE_FILE" logs -f --tail=100 "$service"
  else
    docker compose -f "$COMPOSE_FILE" logs -f --tail=100
  fi
}

cmd_status() {
  check_docker
  docker compose -f "$COMPOSE_FILE" ps
}

cmd_backup() {
  check_docker
  local backup_dir="$SCRIPT_DIR/backups"
  local timestamp
  timestamp="$(date +%Y%m%d_%H%M%S)"
  local backup_file="$backup_dir/rallly_${timestamp}.sql.gz"

  mkdir -p "$backup_dir"

  echo "Backing up database..."
  docker compose -f "$COMPOSE_FILE" exec -T db \
    pg_dump -U postgres rallly | gzip > "$backup_file"

  echo "Backup saved to: $backup_file"
}

cmd_help() {
  cat <<EOF
Rallly Management CLI

Usage: ./rallly.sh <command> [options]

Commands:
  setup          Interactive configuration and secret generation
  start          Start all services
  stop           Stop all services
  restart        Restart all services
  update         Pull latest images and restart
  logs [service] Stream logs (optionally for a specific service)
  status         Show service status
  backup         Back up the database to ./backups/
  help           Show this help message

Services: traefik, rallly, db, redis, serverless-redis-http, garage
EOF
}

case "${1:-help}" in
  setup)   cmd_setup ;;
  start)   cmd_start ;;
  stop)    cmd_stop ;;
  restart) cmd_restart ;;
  update)  cmd_update ;;
  logs)    cmd_logs "${2:-}" ;;
  status)  cmd_status ;;
  backup)  cmd_backup ;;
  help|*)  cmd_help ;;
esac
