#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$SCRIPT_DIR/.env"

# Load .env if it exists
if [ -f "$ENV_FILE" ]; then
  set -a
  # shellcheck disable=SC1091
  source "$ENV_FILE"
  set +a
fi

# Compose file selection: base, plus the external-proxy override when the
# user is bringing their own reverse proxy (PROXY_MODE=external).
_compose_files=("$SCRIPT_DIR/docker-compose.yml")
if [ "${PROXY_MODE:-bundled}" = "external" ]; then
  _compose_files+=("$SCRIPT_DIR/docker-compose.external-proxy.yml")
fi
COMPOSE_FILE="$(IFS=:; echo "${_compose_files[*]}")"
export COMPOSE_FILE
unset _compose_files

# Enable bundled services unless the user has pointed Rallly at external
# providers in .env. Setting S3_ENDPOINT to a non-Garage endpoint disables
# the bundled Garage container; setting DATABASE_URL disables the bundled
# Postgres container; PROXY_MODE=external disables the bundled Traefik.
_profiles=()
if [ -z "${S3_ENDPOINT:-}" ] || [ "${S3_ENDPOINT}" = "http://garage:3900" ]; then
  _profiles+=("bundled-storage")
fi
if [ -z "${DATABASE_URL:-}" ]; then
  _profiles+=("bundled-db")
fi
if [ "${PROXY_MODE:-bundled}" != "external" ]; then
  _profiles+=("bundled-proxy")
fi
COMPOSE_PROFILES="$(IFS=,; echo "${_profiles[*]-}")"
export COMPOSE_PROFILES
unset _profiles

# ── Helpers ─────────────────────────────────────────────────────

info()  { echo "  → $*"; }
error() { echo "  ✗ $*" >&2; }
ok()    { echo "  ✓ $*"; }

prompt() {
  local var_name="$1" prompt_text="$2" default="${3:-}"
  local input
  if [ -n "$default" ]; then
    printf "  %s [%s]: " "$prompt_text" "$default"
  else
    printf "  %s: " "$prompt_text"
  fi
  read -r input
  eval "$var_name=\"${input:-$default}\""
}

prompt_secret() {
  local var_name="$1" prompt_text="$2"
  local input="" char
  printf "  %s: " "$prompt_text"
  while IFS= read -rsn1 char; do
    if [[ -z "$char" ]]; then
      break
    elif [[ "$char" == $'\x7f' || "$char" == $'\b' ]]; then
      if [[ -n "$input" ]]; then
        input="${input%?}"
        printf '\b \b'
      fi
    else
      input+="$char"
      printf '*'
    fi
  done
  echo ""
  eval "$var_name=\"$input\""
}

generate_secret() {
  openssl rand -hex "$1" 2>/dev/null
}

check_docker() {
  if ! command -v docker &>/dev/null; then
    error "Docker is not installed."
    exit 1
  fi
  if ! docker compose version &>/dev/null; then
    error "Docker Compose v2 is not available."
    exit 1
  fi
}

# ── Commands ────────────────────────────────────────────────────

cmd_setup() {
  if [ -f "$ENV_FILE" ]; then
    info "Existing .env found."
    read -rp "  Overwrite with new configuration? [y/N]: " overwrite
    if [[ ! "${overwrite:-N}" =~ ^[Yy]$ ]]; then
      ok "Keeping existing configuration."
      return 0
    fi
  fi

  if ! command -v openssl &>/dev/null; then
    error "openssl is required to generate secrets. Please install it and try again."
    exit 1
  fi

  echo ""
  echo "  ── Configuration ──"
  echo ""

  prompt DOMAIN "Domain name (e.g. rallly.example.com)"
  prompt INITIAL_ADMIN_EMAIL "Admin email (used to log in to the admin panel)"
  prompt SUPPORT_EMAIL "Support email shown to users" "$INITIAL_ADMIN_EMAIL"

  echo ""
  echo "  ── Reverse Proxy ──"
  echo ""
  echo "  1) bundled  — Traefik on this host handles HTTPS (ports 80/443 required)"
  echo "  2) external — You already have a reverse proxy; publish web on a host port"
  echo ""
  prompt PROXY_CHOICE "Choose [1/2]" "1"
  if [ "$PROXY_CHOICE" = "2" ]; then
    PROXY_MODE=external
    prompt WEB_PORT "Host port binding for web" "127.0.0.1:3000"
  else
    PROXY_MODE=bundled
    prompt ACME_EMAIL "Email for SSL certificates" "$INITIAL_ADMIN_EMAIL"
  fi

  echo ""
  echo "  ── Email (SMTP) ──"
  echo ""
  prompt SMTP_HOST "SMTP host"
  prompt SMTP_PORT "SMTP port" "587"
  prompt SMTP_USER "SMTP username"
  prompt_secret SMTP_PWD "SMTP password"

  # Implicit TLS on 465; STARTTLS/plain on everything else (587, 25, 2525, ...)
  if [ "$SMTP_PORT" = "465" ]; then
    SMTP_SECURE=true
  else
    SMTP_SECURE=false
  fi

  echo ""
  info "Generating secrets..."

  local secret_password postgres_password s3_access_key s3_secret_key
  secret_password="$(generate_secret 32)"
  postgres_password="$(generate_secret 24)"
  s3_access_key="$(generate_secret 16)"
  s3_secret_key="$(generate_secret 32)"

  {
    cat <<ENVEOF
# Rallly Self-Hosted Configuration
# Generated by rallly.sh setup on $(date -u +"%Y-%m-%dT%H:%M:%SZ")

# ── Domain ──
DOMAIN=$DOMAIN

# ── Reverse Proxy ──
PROXY_MODE=$PROXY_MODE
ENVEOF

    if [ "$PROXY_MODE" = "bundled" ]; then
      cat <<ENVEOF
ACME_EMAIL=$ACME_EMAIL
ENVEOF
    else
      cat <<ENVEOF
WEB_PORT=$WEB_PORT
ENVEOF
    fi

    cat <<ENVEOF

# ── App Settings ──
SECRET_PASSWORD=$secret_password
SUPPORT_EMAIL=$SUPPORT_EMAIL
INITIAL_ADMIN_EMAIL=$INITIAL_ADMIN_EMAIL

# ── SMTP ──
SMTP_HOST=$SMTP_HOST
SMTP_PORT=$SMTP_PORT
SMTP_SECURE=$SMTP_SECURE
SMTP_USER=$SMTP_USER
SMTP_PWD=$SMTP_PWD

# ── Auto-configured ──
POSTGRES_PASSWORD=$postgres_password
S3_ACCESS_KEY_ID=$s3_access_key
S3_SECRET_ACCESS_KEY=$s3_secret_key
ENVEOF
  } > "$ENV_FILE"

  chmod 600 "$ENV_FILE"
  ok "Configuration saved to $ENV_FILE"
}

cmd_start() {
  check_docker
  if [ ! -f "$ENV_FILE" ]; then
    error "No .env file found. Run './rallly.sh setup' first."
    exit 1
  fi
  docker compose up -d
  echo ""
  echo "Rallly is starting at https://${DOMAIN:-localhost}"
  echo "Run './rallly.sh logs' to watch startup progress."
}

cmd_stop() {
  check_docker
  docker compose down
  echo "Rallly has been stopped."
}

cmd_restart() {
  check_docker
  docker compose restart
  echo "Rallly has been restarted."
}

cmd_update() {
  check_docker
  # Update repo files if this is a git clone
  if [ -d "$SCRIPT_DIR/.git" ]; then
    echo "Updating configuration files..."
    git -C "$SCRIPT_DIR" pull --ff-only || {
      error "Could not update repo files. You may need to run: git -C $SCRIPT_DIR pull manually."
    }
    echo ""
  fi
  echo "Pulling latest images..."
  docker compose pull
  echo ""
  echo "Recreating containers..."
  docker compose up -d --remove-orphans
  echo ""
  echo "Update complete."
  docker compose ps
}

cmd_logs() {
  check_docker
  local service="${1:-}"
  if [ -n "$service" ]; then
    docker compose logs -f --tail=100 "$service"
  else
    docker compose logs -f --tail=100
  fi
}

cmd_status() {
  check_docker
  docker compose ps
}

cmd_backup() {
  check_docker
  local backup_dir="$SCRIPT_DIR/backups"
  local timestamp
  timestamp="$(date +%Y%m%d_%H%M%S)"
  local backup_file="$backup_dir/rallly_${timestamp}.sql.gz"

  mkdir -p "$backup_dir"

  echo "Backing up database..."
  if [ -z "${DATABASE_URL:-}" ]; then
    docker compose exec -T db \
      pg_dump -U postgres rallly | gzip > "$backup_file"
  else
    # External Postgres — run pg_dump in a throwaway container.
    # Uses the same major version as the bundled image; for newer server
    # versions you may need to run pg_dump manually with a matching client.
    docker run --rm -i postgres:14-alpine \
      pg_dump "$DATABASE_URL" | gzip > "$backup_file"
  fi

  echo "Backup saved to: $backup_file"
}

cmd_help() {
  cat <<EOF
Rallly Management CLI

Usage: ./rallly.sh <command> [options]

Commands:
  setup          Interactive configuration and secret generation
  start          Start all services
  stop           Stop all services
  restart        Restart all services
  update         Pull latest images and restart
  logs [service] Stream logs (optionally for a specific service)
  status         Show service status
  backup         Back up the database to ./backups/
  help           Show this help message

Services: traefik, web, db, garage
EOF
}

case "${1:-help}" in
  setup)   cmd_setup ;;
  start)   cmd_start ;;
  stop)    cmd_stop ;;
  restart) cmd_restart ;;
  update)  cmd_update ;;
  logs)    cmd_logs "${2:-}" ;;
  status)  cmd_status ;;
  backup)  cmd_backup ;;
  help|*)  cmd_help ;;
esac
