{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rallly.postgresql.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rallly.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.postgresql.username | quote }}
  POSTGRES_PASSWORD: {{ include "rallly.generateSecret" (dict "context" . "value" .Values.postgresql.password "secretName" (include "rallly.postgresql.secretName" .) "key" "POSTGRES_PASSWORD" "length" 32) | quote }}
  POSTGRES_DB: {{ .Values.postgresql.database | quote }}
{{- end }}
